class Solution {
public:
    int countTriples(int n) {
        // from 1 to n: 
        // how many x, y and z exist such that: they follow the
        // pythagores theorem : a^2 + b^2 = c^2;

        // since the range of n: [1,250] we can brute force this
        // int ans = 0;
        // for(int a=1;a<=n;a++){
        //     for(int b=1;b<=n;b++){
        //         int c = a*a + b*b;
        //         int c_sqrt = sqrt(c);
        //         if(c_sqrt<=n and c == c_sqrt*c_sqrt)ans++;
                
        //     }
        // }
        // return ans;

        // better approach: 
        // using euclids formula from number theroy: 
        // euclid formula: 
        // Euclid's formula states that for two integers m and k where m>k>0, a
        // primitive Pythagorean triple (a,b,c) can be generated by:
        // a = m^2 - k^2;
        // b = 2mk;
        // c = m^2 + k^2;

        // For the triple to be primitive (meaning gcd(a,b,c)=1), 
        // two conditions must be met:
        // 1. gcd(m,k)=1 (m and k are coprime).
        // 2. m−k is odd (one is even, the other is odd).
        // Once we generate a primitive triple (a,b,c) with c≤n, 
        // any multiple (d⋅a,d⋅b,d⋅c) is also a valid square triple as long as d⋅c≤n. 
        // The number of such multiples is simply ⌊n/c⌋.

        // Since we need to account for both (a,b,c) and (b,a,c), we multiply the count by 2.
        int ans = 0;
        for(int m = 2;m*m<=n;m++){
            for(int k = 1;k<=m;k++){
                if(gcd(m,k)==1 and (m-k)%2==1){
                    int c_primitive = m*m +k*k;
                    if(c_primitive>n)break;
                    ans += 2*(n/c_primitive);
                }
            }
        }
        return ans;

    }
};